# SPDX-FileCopyrightText: 2025 Aindo SpA
#
# SPDX-License-Identifier: MIT

name: Main CI flow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  pre-commit:
    name: Run pre-commit checks
    uses: ./.github/workflows/pre-commit.yml

  tests:
    name: Run tests for Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    uses: ./.github/workflows/tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      skip-coverage: ${{ matrix.python-version != '3.10' }} # Run coverage analysis only once.

  docs-build:
    name: Build and verify docs
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Install requirements
        run: pip install -r docs/requirements.txt
        
      - name: Build documentation
        run: mkdocs build 

  docs-publish:
    name: Publish documentation for version 'dev'
    needs: [pre-commit, tests]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/docs-update.yml
